openapi: 3.0.1
info:
  title: Stack Analyses API
  version: "2.0"
servers:
  - url: https://f8a-analytics-2445582058137.{environment}.gw.apicast.io/api/v2
    variables:
      environment:
        default: production # Production server
        enum:
          - production # Production server
          - staging # Staging server

security: # All endpoints needs 3scale user_key, refer securitySchemes
  - tokenAuth: []

paths:
  /stack-analyses:
    post:
      tags:
      - Scan Services
      summary: Initiates a scan to gather security and other details about an application
        stack and related recommendations to improve the stack
      parameters:
      - name: ecosystem
        in: header
        description: The ecosystem of the stack analysis being called.
        required: true
        schema:
          $ref: '#/components/schemas/Ecosystem'
      - name: origin
        in: header
        description: This is required to give an indication as to from where is the
          request getting generated. If from VScode extension, the value which we
          need to send is 'vscode'.
        schema:
          type: string
          default: vscode
          enum:
            - vscode
      - name: show_transitive
        in: header
        description: This is required to enable or disable the transitive support.
          We need to pass the value as 'true' if transitive is needed. Default value
          is 'false'.
        schema:
          type: boolean
          default: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - filePath[]
              - manifest[]
              properties:
                manifest[]:
                  type: string
                  description: A manifest file dependencies.txt for maven, npmlist.json
                    for npm & pylist.json for pypi. Commands to generate these files
                    are mentioned in the README.md
                  format: binary
                filePath[]:
                  type: string
                  description: The absolute or relative path where the manifest file
                    is located. This has to be mandatorily provided with the manifest[]
                    parameter and vice versa.
        required: true
      responses:
        200:
          description: Response with the unique identifier for the stack analysis
            request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserStackIdentifier'
        400:
          description: Bad request
          content: {}
        401:
          description: Request Unauthorized
          content: {}

  /stack-analyses/{request-id}:
    get:
      tags:
      - Scan Services
      summary: Get security and other details about an application stack and related
        recommendations to improve the stack
      parameters:
      - name: request-id
        in: path
        description: stack analysis request id
        required: true
        schema:
          type: string
          example: 478eb2dedca34dbc80146805e08e31b4
      responses:
        200:
          description: Detailed response for the requested application component
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StackAnalysesReport'
        202:
          description: Report generation is inprogress
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
                    example: Analysis for request ID '478eb2dedca34dbc80146805e08e31b4' is in progress
        401:
          description: Request unauthorized
          content: {}
        404:
          description: Data not found
          content: {}
        408:
          description: Request has timed out on server
          content: {}
components:
  schemas:
    Ecosystem:
      title: Ecosystem
      type: string
      enum:
        - maven
        - pypi
        - npm
      description: List of supported package ecosystems

    BasicVulnerabilityFields:
      title: VulnerabilityBase
      properties:
        cvss:
          type: number
          format: float
          example: 9.8
        cvss_v3:
          type: string
          example: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
        severity:
          type: string
          enum:
            - low
            - medium
            - high
            - critical
        title:
          type: string
          example: SQL Injection
        id:
          type: string
          example: SNYK-PYTHON-DJANGO-40027
        url:
          type: string
          example: https://snyk.io/vuln/SNYK-PYTHON-DJANGO-4002
      description: Limited private vulnerability details for free tier users

    PremiumVulnerabilityFields:
      title: PremiumVulnerabilityFields
      type: object
      properties:
        malicious:
          type: boolean
          default: true
        patch_exists:
          type: boolean
          default: false
          example: true
        fixable:
          type: boolean
          default: false
          example: true
        exploit:
          type: string
          example: High
        description:
          type: string
          example: |
            "## Overview\r\n[`django`](https://pypi.python.org/pypi/django) is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.\r\n\r\nAffected versions of this package expose sensitive information due to not properly restricting the use of a query string that performs certain object filtering. An attacker may obtain sensitive information via a series of requests containing regular expressions, as demonstrated by a `created_by__password__regex` parameter.\r\n\r\n## References\r\n- [Django Vulnerability Description](http://www.djangoproject.com/weblog/2010/dec/22/security/)\r\n- [GitHub Commit](https://github.com/django/django/commit/732198ed5c)\r\n- [Redhat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=665373)\r\n- [Openwall](http://www.openwall.com/lists/oss-security/2011/01/03/5)\r\n- [CVE](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2010-4534)\r\n"
        fixed_in:
          type: array
          items:
            type: string
          example:
            - 2.6.7
            - 2.7.5
            - 2.8.0
        references:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
                example: Redhat Security Advisory
              url:
                type: string
                example: https://access.redhat.com/security/cve/CVE-2013-2186
      description: |
        Extended Vulnerability details, available only to registered users

    PublicVulnerabilityDetails:
      title: PublicVulnerabilityDetails
      description: |
        Publicaly known Vulnerability details with associated CVES
      allOf:
        - $ref: '#/components/schemas/BasicVulnerabilityFields'
        - type: object
          properties:
            cve_ids:
              type: array
              items:
                type: string
              example: 
                - CVE-2014-0474
                - CVE-2014-0475

    PrivateVulnerabilityDetails:
      title: PrivateVulnerabilityDetails
      allOf:
        - $ref: '#/components/schemas/BasicVulnerabilityFields'
      description: Private vulnerability details

    LimitedPrivateVulnerabilityDetails:
      title: LimitedPrivateVulnerabilityDetails
      allOf:
        - $ref: '#/components/schemas/BasicVulnerabilityFields'
      description: Basic private vulnerability details

    Package:
      title: Package
      type: object
      properties:
        name:
          type: string
          example: django
        version:
          type: string
          example: 1.2.1
      description: Package details

    PackageWithTransitives:
      title: PackageWithTransitives
      allOf:
        - $ref: '#/components/schemas/Package'
        - type: object
          properties:
            deps:
              type: array
              items:
                $ref: '#/components/schemas/Package'
              example:
                - requests:
                    name: requests
                    version: 1.2.3
                - six:
                    name: six
                    version: 5.1.1
      description: Package details with transitives

    UnknownLicenses:
      title: UnknownLicenses
      type: object
      properties:
        component_conflict:
          type: array
          items:
            type: object
            properties:
              license1:
                type: string
                example: BSD License (BSD)
              license2:
                type: string
                example: General Public License V3(GPL)
        really_unknown:
          type: array
          items:
            type: object
            properties:
              package:
                type: string
                example: django
              license:
                type: string
                example: BSD License (BSD)
      description: Data of licenses unknown to the system

    ConflictPackages:
      title: ConflictPackages
      type: object
      properties:
        package1:
          type: string
          example: django
        license1:
          type: string
          example: BSD License (BSD)
        package2:
          type: string
          example: rustdoc
        license2: 
          type: string
          example: General Public License V3(GPL)
      description: Pair of packages which has conflict in license

    LicenseAnalysis:
      title: LicenseAnalysis
      type: object
      properties:
        outlier_packages:
          type: array
          items:
            type: object
            properties: {}
        conflict_packages:
          type: array
          items:
            $ref: '#/components/schemas/ConflictPackages'
        current_stack_license:
          type: object
          properties: {}
        unknown_licenses:
          $ref: '#/components/schemas/UnknownLicenses'
      description: License analyses data

    GitHubDetails:
      title: GitHubDetails
      type: object
      properties:
        watchers:
          type: integer
          example: 1002
        first_release_date:
          type: string
        total_releases:
          type: integer
          example: 12
        issues:
          type: object
          properties: {}
        pull_requests:
          type: object
          properties: {}
        dependent_repos:
          type: integer
        open_issues_count:
          type: integer
        latest_release_duration:
          type: string
        forks_count:
          type: integer
          example: 123
        contributors:
          type: integer
          example: 12
        size:
          type: string
        stargazers_count:
          type: integer
          example: 50000
        used_by:
          type: array
          items:
            type: string
        dependent_projects:
          type: integer
          example: 1534
      description: Github details

    PackageDetailsBase:
      title: PackageDetailsBase
      allOf:
        - $ref: '#/components/schemas/Package'
        - type: object
          properties:
            latest_version:
              type: string
              example: 3.0.5
            github:
              $ref: '#/components/schemas/GitHubDetails'
            licenses:
              type: array
              items:
                type: string
              example:
                - Apache License, Version 2.0
            topic_list:
              type: array
              items:
                type: string
            ecosystem:
              $ref: '#/components/schemas/Ecosystem'
            public_vulnerabilities_count:
              type: integer
              example: 21
            private_vulnerabilities_count:
              type: integer
              example: 3
            affected_direct_deps:
              type: array
              description: Lists all direct dependencies of this package
              items:
                $ref: '#/components/schemas/Package'
              example:
                - name: jinja2
                  version: 2.5.2
                - name: django-orm
                  version: 7.1.0
            osio_user_count:
              type: integer
              example: 123
          description: Details of the package

    RecommendedVersionForPublicVulnerabilities:
      title: RecommendedVersionForPublicVulnerabilities
      properties:
        recommended_version:
            type: string
            example: 3.0.0
      description: |
        Recommended package version which includes only fix public vulnerability

    RecommendedVersionForPublicAndPrivateVulnerabilities:
      title: RecommendedVersionForPublicAndPrivateVulnerabilities
      properties:
        recommended_version:
            type: string
            example: 3.0.0
      description: |
        Recommended package version which includes fix for public and private vulnerability

    PackageDetailsForRegisteredUser:
      title: PackageDetailsForRegisteredUser
      allOf:
        - $ref: '#/components/schemas/PackageDetailsBase'
        - $ref: '#/components/schemas/RecommendedVersionForPublicAndPrivateVulnerabilities'
        - type: object
          properties:
            public_vulnerabilities:
              type: array
              description: Publicly known vulnerability details
              items:
                allOf:
                  - $ref: '#/components/schemas/PremiumVulnerabilityFields'
                  - $ref: '#/components/schemas/PublicVulnerabilityDetails'
            private_vulnerabilities:
              type: array
              description: |
                Private vulnerability details, available only to registered
                users
              items:
                allOf:
                  - $ref: '#/components/schemas/PremiumVulnerabilityFields'
                  - $ref: '#/components/schemas/PrivateVulnerabilityDetails'
          description: Details of the package for registered users

    PackageDetailsForFreeTier:
      title: PackageDetailsForFreeTier
      allOf:
        - $ref: '#/components/schemas/PackageDetailsBase'
        - $ref: '#/components/schemas/RecommendedVersionForPublicVulnerabilities'
        - type: object
          properties:
            public_vulnerabilities:
              type: array
              description: Publicly known vulnerability details
              items:
                $ref: '#/components/schemas/PublicVulnerabilityDetails'
            private_vulnerabilities:
              type: array
              description: Private vulnerability details with limited info
              items:
                $ref: '#/components/schemas/LimitedPrivateVulnerabilityDetails'
          description: Details of the package for free tier users

    RecommendedPackageData:
      title: RecommendedPackageData
      description: Recommended packages data
      allOf:
      - oneOf:
        - $ref: '#/components/schemas/PackageDetailsForFreeTier'
        - $ref: '#/components/schemas/PackageDetailsForRegisteredUser'
      - type: object
        properties:
          confidence_reason:
            type: number
            format: float
            example: 83.16431
          reason:
            type: string
          topic_list:
            type: array
            items:
              type: string

    StackRecommendation:
      title: StackRecommendation
      type: object
      properties:
        companion:
          type: array
          items:
            $ref: '#/components/schemas/RecommendedPackageData'
        manifest_file_path:
          type: string
          example: pom.xml
        usage_outliers:
          type: array
          items:
            type: object
            properties: {}
      description: Application stack recommendations

    StackAnalysesResult:
      title: StackAnalysesResult
      type: object
      properties:
        manifest_file_path:
          type: string
          example: pom.xml
        manifest_name:
          type: string
          example: dependencies.txt
        unknown_dependencies:
          type: array
          items:
            $ref: '#/components/schemas/Package'
          example:
            - name: rocket-db
              version: 2020.1.alpha
            - name: jsonp
              version: 0.0.1
        ecosystem:
          $ref: '#/components/schemas/Ecosystem'
        unknown_dependencies_count:
          type: integer
          example: 2
        analyzed_dependencies:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/PackageDetailsForFreeTier'
              - $ref: '#/components/schemas/PackageDetailsForRegisteredUser'
        analyzed_dependencies_count:
          type: integer
          example: 25
        license_analysis:
          $ref: '#/components/schemas/LicenseAnalysis'
        distinct_licenses:
          type: array
          items:
            type: string
        stack_license_conflict:
          type: boolean
        dependencies:
          type: array
          items:
            $ref: '#/components/schemas/PackageWithTransitives'
        total_licenses:
          type: integer
          example: 15
        recommendation_ready:
          type: boolean  
        recommendation:
          $ref: '#/components/schemas/StackRecommendation'
      description: Stack analyses result data

    StackAnalysesReport:
      title: StackAnalysesReport
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/StackAnalysesResult'
      description: Response structure for stack analyses

    UserStackIdentifier:
      title: UserStackIdentifier
      type: object
      properties:
        id:
          type: string
          example: 229e7da76708fe374d8c10fa752e72989f
        status:
          type: string
          example: success
        submitted_at:
          type: string
          example: 2020-04-06 11:56:08.349405
      description: Response structure for stack analyses post call

  securitySchemes:
    tokenAuth:
      type: apiKey
      description: 3Scale user key
      name: user_key
      in: query